In [1]:
import numpy as np
import pandas as pd
import os
ratings= pd.read_csv('interactions.csv')
ratings.head()

     id  user  path    rating
0   491     1     3  3.741418
1  3326     1     5  1.323232
2  1164     1    13  3.057498
3  4132     1    13  4.008407
4  3159     1    18  3.901063

In [2]:
paths = pd.read_csv('paths.csv')

In [3]:
paths_data=paths.merge(ratings,left_on='pathId',right_on='path')

In [4]:
ratings_mean_count = pd.DataFrame(paths_data.groupby('title')['rating'].mean())

In [5]:
ratings_mean_count.head()

           rating
title
path1    2.241636
path10   2.255923
path100  2.382515
path101  3.108236
path102  2.224628

In [6]:
ratings_mean_count['rating_counts'] = pd.DataFrame(paths_data.groupby('title')['rating'].count())

In [7]:
ratings_mean_count.head()

           rating  rating_counts
title
path1    2.241636              9
path10   2.255923             11
path100  2.382515             14
path101  3.108236             13
path102  2.224628             15

In [8]:
user_path_rating=paths_data.pivot_table(index='user',columns='title', values='rating')

In [9]:
user_path_rating.head()

title,path1,path10,path100,path101,path102,path103,path104,path105,path106,path107,...,path90,path91,path92,path93,path94,path95,path96,path97,path98,path99
user,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.626896,NaN,...,4.903000,4.085634,4.600377,NaN,3.657116,NaN,3.277865,NaN,NaN,NaN
2,1.173099,NaN,NaN,0.670411,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.609311,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,2.681508,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.640151,0.197846,NaN,2.973621,2.835528,NaN,1.994622,NaN,NaN,NaN
4,NaN,3.088321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,0.130695,2.004951,NaN,NaN,NaN,NaN,NaN,2.809237,NaN,...,NaN,3.164299,NaN,NaN,NaN,0.679811,2.925057,NaN,NaN,NaN

In [10]:
path1=user_path_rating['path40']
path1.head()

user
1         NaN
2         NaN
3    4.013093
4    2.697409
5         NaN
Name: path40, dtype: float64

In [11]:
path1.head()

user
1         NaN
2         NaN
3    4.013093
4    2.697409
5         NaN
Name: path40, dtype: float64

In [12]:
paths_like_path1=user_path_rating.corrwith(path1)

/home/ubuntu/Multidisciplinary-project/Implementation/venv/lib/python3.6/site-packages/numpy/lib/function_base.py:2522: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/home/ubuntu/Multidisciplinary-project/Implementation/venv/lib/python3.6/site-packages/numpy/lib/function_base.py:2451: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

In [13]:
corr_path1 = pd.DataFrame(paths_like_path1, columns=['Correlation'])  
corr_path1.dropna(inplace=True)  
corr_path1.head()

         Correlation
title
path10      0.054104
path100     1.000000
path102     1.000000
path103    -1.000000
path105    -0.946784

In [14]:
corr_path1.sort_values('Correlation', ascending=False).head(10)

         Correlation
title
path20           1.0
path36           1.0
path208          1.0
path207          1.0
path206          1.0
path204          1.0
path293          1.0
path310          1.0
path44           1.0
path156          1.0

In [15]:
corr_path1 = corr_path1.join(ratings_mean_count['rating_counts'])

In [16]:
corr_path1.head()

         Correlation  rating_counts
title
path10      0.054104             11
path100     1.000000             14
path102     1.000000             15
path103    -1.000000              9
path105    -0.946784             10

In [26]:
corr=corr_path1[corr_path1['rating_counts']>12].sort_values('Correlation', ascending=False)

In [27]:
corr['path_title']=corr.index

In [28]:
corr.head()

         Correlation  rating_counts path_title
title
path100          1.0             14    path100
path356          1.0             14    path356
path214          1.0             16    path214
path208          1.0             13    path208
path20           1.0             15     path20

In [29]:
d=paths_data

In [30]:
d

,time_zone,begin,end,pathId,title,id,user,path,rating
8,2016-04-08 11:28:14.000000,1.460115e+12,1.460115e+12,1,path1,559,48,1,2.141448
17,2016-04-11 10:06:44.000000,1.460369e+12,1.460370e+12,2,path2,4014,49,2,0.522813
32,2016-04-11 10:41:57.000000,1.460371e+12,1.460372e+12,3,path3,3030,48,3,1.510361
46,2016-04-12 10:48:30.000000,1.460458e+12,1.460458e+12,4,path4,962,37,4,3.712304
56,2016-04-12 11:07:58.000000,1.460459e+12,1.460460e+12,5,path5,2962,38,5,4.042141
68,2016-04-13 10:06:48.000000,1.460542e+12,1.460543e+12,6,path6,3241,47,6,3.212161
85,2016-04-13 10:28:37.000000,1.460543e+12,1.460545e+12,7,path7,1576,44,7,4.544356
98,2016-04-13 12:36:46.000000,1.460551e+12,1.460552e+12,8,path8,2330,43,8,0.911947
109,2016-04-13 13:06:55.000000,1.460553e+12,1.460553e+12,9,path9,4306,42,9,3.153337
120,2016-04-14 10:35:28.000000,1.460630e+12,1.460631e+12,10,path10,2010,47,10,1.300081
132,2016-04-14 10:57:19.000000,1.460631e+12,1.460632e+12,11,path11,4065,39,11,0.121980
139,2016-04-14 12:15:35.000000,1.460636e+12,1.460636e+12,12,path12,2191,46,12,3.595591
155,2016-04-14 12:18:20.000000,1.460636e+12,1.460636e+12,13,path13,2703,49,13,2.813101
162,2016-04-20 08:36:23.000000,1.461141e+12,1.461142e+12,14,path14,4794,35,14,0.758956
176,2016-04-21 16:10:45.000000,1.461255e+12,1.461255e+12,15,path15,211,50,15,0.220596
192,2016-05-26 17:12:58.000000,1.464283e+12,1.464283e+12,16,path16,2241,50,16,3.257439
204,2016-05-27 06:12:53.000000,1.464330e+12,1.464330e+12,17,path17,797,48,17,1.946060
217,2016-06-23 08:30:40.000000,1.466671e+12,1.466671e+12,18,path18,813,48,18,2.042635
223,2016-06-23 08:31:20.000000,1.466671e+12,1.466671e+12,19,path19,1771,43,19,2.131581
238,2016-06-23 08:35:24.000000,1.466671e+12,1.466671e+12,20,path20,2343,50,20,1.963985
252,2016-06-23 08:35:51.000000,1.466671e+12,1.466671e+12,21,path21,59,46,21,2.989189
266,2016-06-23 08:36:25.000000,1.466671e+12,1.466671e+12,22,path22,1241,49,22,3.035122
275,2016-06-23 08:36:53.000000,1.466671e+12,1.466671e+12,23,path23,2298,48,23,3.231564
286,2016-06-23 09:42:39.000000,1.466675e+12,1.466675e+12,24,path24,3183,41,24,1.172129
299,2016-06-23 10:31:59.000000,1.466678e+12,1.466678e+12,25,path25,1580,49,25,3.578945
315,2016-06-23 10:32:35.000000,1.466678e+12,1.466678e+12,26,path26,945,49,26,4.534497
328,2016-06-23 16:09:03.000000,1.466698e+12,1.466698e+12,27,path27,3712,47,27,1.408119
336,2016-06-23 16:09:15.000000,1.466698e+12,1.466698e+12,28,path28,1035,45,28,1.693743
345,2016-06-23 16:09:26.000000,1.466698e+12,1.466698e+12,29,path29,3651,45,29,0.879261
359,2016-06-23 16:09:48.000000,1.466698e+12,1.466698e+12,30,path30,3506,40,30,2.602429
...,...,...,...,...,...,...,...,...,...
4685,2017-07-03 11:18:55.000000,1.499081e+12,1.499081e+12,407,path407,4644,43,407,0.258729
4694,2017-07-06 08:26:09.000000,1.499330e+12,1.499330e+12,408,path408,4037,48,408,3.822086
4702,2017-07-06 09:39:27.000000,1.499334e+12,1.499334e+12,409,path409,1748,46,409,0.849554
4717,2017-07-07 19:11:25.000000,1.499455e+12,1.499457e+12,410,path410,3590,46,410,0.532039
4726,2017-09-28 07:32:22.000000,1.506588e+12,1.506589e+12,411,path411,1077,50,411,3.522986
4739,2017-09-28 08:20:06.000000,1.506590e+12,1.506592e+12,412,path412,4665,50,412,2.895333
4751,2017-09-28 08:31:51.000000,1.506588e+12,1.506589e+12,413,path413,2210,49,413,4.476490
4766,2017-09-28 08:32:35.000000,1.506588e+12,1.506591e+12,414,path414,1019,50,414,2.152092
4778,2017-09-28 08:32:54.000000,1.506588e+12,1.506590e+12,415,path415,1995,49,415,2.134702
4789,2017-09-28 08:33:41.000000,1.506588e+12,1.506592e+12,416,path416,4535,47,416,4.424576
4810,2017-09-28 08:33:53.000000,1.506588e+12,1.506589e+12,417,path417,1058,49,417,3.196748
4816,2017-09-28 08:58:34.000000,1.506589e+12,1.506590e+12,418,path418,3794,48,418,2.545599
4824,2017-09-28 09:00:02.000000,1.506589e+12,1.506590e+12,419,path419,1798,50,419,0.483211
4839,2017-09-28 09:00:04.000000,1.506589e+12,1.506590e+12,420,path420,240,45,420,3.305387
4847,2017-09-28 09:09:13.000000,1.506590e+12,1.506590e+12,421,path421,4991,49,421,0.307045
4853,2017-09-28 09:12:19.000000,1.506590e+12,1.506592e+12,422,path422,3466,36,422,2.614872
4865,2017-09-28 09:16:36.000000,1.506590e+12,1.506591e+12,423,path423,1143,50,423,2.179242
4875,2017-09-28 09:19:34.000000,1.506590e+12,1.506592e+12,424,path424,804,50,424,4.159896
4884,2017-09-28 09:20:07.000000,1.506590e+12,1.506591e+12,425,path425,118,48,425,4.295584
4891,2017-09-28 09:21:21.000000,1.506590e+12,1.506591e+12,426,path426,1152,37,426,1.170371
4900,2017-09-28 09:26:47.000000,1.506591e+12,1.506591e+12,427,path427,3964,44,427,2.479762
4909,2017-09-28 09:28:19.000000,1.506591e+12,1.506591e+12,428,path428,593,41,428,1.204016
4918,2017-09-28 09:31:08.000000,1.506591e+12,1.506592e+12,429,path429,510,41,429,3.611573
4923,2017-09-28 09:32:17.000000,1.506591e+12,1.506591e+12,430,path430,3343,31,430,2.908970
4937,2017-09-28 09:32:18.000000,1.506591e+12,1.506591e+12,431,path431,1404,48,431,0.540352
4949,2017-09-28 09:35:44.000000,1.506591e+12,1.506592e+12,432,path432,3678,48,432,2.994662
4957,2017-09-28 10:38:45.000000,1.506595e+12,1.506596e+12,433,path433,2277,49,433,4.449664
4967,2017-09-28 10:39:02.000000,1.506595e+12,1.506596e+12,434,path434,1842,49,434,0.678919
4981,2017-09-28 10:43:10.000000,1.506596e+12,1.506596e+12,435,path435,684,50,435,4.968631
4998,2017-09-28 10:44:16.000000,1.506596e+12,1.506596e+12,436,path436,1655,50,436,1.669602

In [31]:
d.drop_duplicates(subset ="time_zone", keep = 'last', inplace = True)

In [32]:
d

,time_zone,begin,end,pathId,title,id,user,path,rating
8,2016-04-08 11:28:14.000000,1.460115e+12,1.460115e+12,1,path1,559,48,1,2.141448
17,2016-04-11 10:06:44.000000,1.460369e+12,1.460370e+12,2,path2,4014,49,2,0.522813
32,2016-04-11 10:41:57.000000,1.460371e+12,1.460372e+12,3,path3,3030,48,3,1.510361
46,2016-04-12 10:48:30.000000,1.460458e+12,1.460458e+12,4,path4,962,37,4,3.712304
56,2016-04-12 11:07:58.000000,1.460459e+12,1.460460e+12,5,path5,2962,38,5,4.042141
68,2016-04-13 10:06:48.000000,1.460542e+12,1.460543e+12,6,path6,3241,47,6,3.212161
85,2016-04-13 10:28:37.000000,1.460543e+12,1.460545e+12,7,path7,1576,44,7,4.544356
98,2016-04-13 12:36:46.000000,1.460551e+12,1.460552e+12,8,path8,2330,43,8,0.911947
109,2016-04-13 13:06:55.000000,1.460553e+12,1.460553e+12,9,path9,4306,42,9,3.153337
120,2016-04-14 10:35:28.000000,1.460630e+12,1.460631e+12,10,path10,2010,47,10,1.300081
132,2016-04-14 10:57:19.000000,1.460631e+12,1.460632e+12,11,path11,4065,39,11,0.121980
139,2016-04-14 12:15:35.000000,1.460636e+12,1.460636e+12,12,path12,2191,46,12,3.595591
155,2016-04-14 12:18:20.000000,1.460636e+12,1.460636e+12,13,path13,2703,49,13,2.813101
162,2016-04-20 08:36:23.000000,1.461141e+12,1.461142e+12,14,path14,4794,35,14,0.758956
176,2016-04-21 16:10:45.000000,1.461255e+12,1.461255e+12,15,path15,211,50,15,0.220596
192,2016-05-26 17:12:58.000000,1.464283e+12,1.464283e+12,16,path16,2241,50,16,3.257439
204,2016-05-27 06:12:53.000000,1.464330e+12,1.464330e+12,17,path17,797,48,17,1.946060
217,2016-06-23 08:30:40.000000,1.466671e+12,1.466671e+12,18,path18,813,48,18,2.042635
223,2016-06-23 08:31:20.000000,1.466671e+12,1.466671e+12,19,path19,1771,43,19,2.131581
238,2016-06-23 08:35:24.000000,1.466671e+12,1.466671e+12,20,path20,2343,50,20,1.963985
252,2016-06-23 08:35:51.000000,1.466671e+12,1.466671e+12,21,path21,59,46,21,2.989189
266,2016-06-23 08:36:25.000000,1.466671e+12,1.466671e+12,22,path22,1241,49,22,3.035122
275,2016-06-23 08:36:53.000000,1.466671e+12,1.466671e+12,23,path23,2298,48,23,3.231564
286,2016-06-23 09:42:39.000000,1.466675e+12,1.466675e+12,24,path24,3183,41,24,1.172129
299,2016-06-23 10:31:59.000000,1.466678e+12,1.466678e+12,25,path25,1580,49,25,3.578945
315,2016-06-23 10:32:35.000000,1.466678e+12,1.466678e+12,26,path26,945,49,26,4.534497
328,2016-06-23 16:09:03.000000,1.466698e+12,1.466698e+12,27,path27,3712,47,27,1.408119
336,2016-06-23 16:09:15.000000,1.466698e+12,1.466698e+12,28,path28,1035,45,28,1.693743
345,2016-06-23 16:09:26.000000,1.466698e+12,1.466698e+12,29,path29,3651,45,29,0.879261
359,2016-06-23 16:09:48.000000,1.466698e+12,1.466698e+12,30,path30,3506,40,30,2.602429
...,...,...,...,...,...,...,...,...,...
4685,2017-07-03 11:18:55.000000,1.499081e+12,1.499081e+12,407,path407,4644,43,407,0.258729
4694,2017-07-06 08:26:09.000000,1.499330e+12,1.499330e+12,408,path408,4037,48,408,3.822086
4702,2017-07-06 09:39:27.000000,1.499334e+12,1.499334e+12,409,path409,1748,46,409,0.849554
4717,2017-07-07 19:11:25.000000,1.499455e+12,1.499457e+12,410,path410,3590,46,410,0.532039
4726,2017-09-28 07:32:22.000000,1.506588e+12,1.506589e+12,411,path411,1077,50,411,3.522986
4739,2017-09-28 08:20:06.000000,1.506590e+12,1.506592e+12,412,path412,4665,50,412,2.895333
4751,2017-09-28 08:31:51.000000,1.506588e+12,1.506589e+12,413,path413,2210,49,413,4.476490
4766,2017-09-28 08:32:35.000000,1.506588e+12,1.506591e+12,414,path414,1019,50,414,2.152092
4778,2017-09-28 08:32:54.000000,1.506588e+12,1.506590e+12,415,path415,1995,49,415,2.134702
4789,2017-09-28 08:33:41.000000,1.506588e+12,1.506592e+12,416,path416,4535,47,416,4.424576
4810,2017-09-28 08:33:53.000000,1.506588e+12,1.506589e+12,417,path417,1058,49,417,3.196748
4816,2017-09-28 08:58:34.000000,1.506589e+12,1.506590e+12,418,path418,3794,48,418,2.545599
4824,2017-09-28 09:00:02.000000,1.506589e+12,1.506590e+12,419,path419,1798,50,419,0.483211
4839,2017-09-28 09:00:04.000000,1.506589e+12,1.506590e+12,420,path420,240,45,420,3.305387
4847,2017-09-28 09:09:13.000000,1.506590e+12,1.506590e+12,421,path421,4991,49,421,0.307045
4853,2017-09-28 09:12:19.000000,1.506590e+12,1.506592e+12,422,path422,3466,36,422,2.614872
4865,2017-09-28 09:16:36.000000,1.506590e+12,1.506591e+12,423,path423,1143,50,423,2.179242
4875,2017-09-28 09:19:34.000000,1.506590e+12,1.506592e+12,424,path424,804,50,424,4.159896
4884,2017-09-28 09:20:07.000000,1.506590e+12,1.506591e+12,425,path425,118,48,425,4.295584
4891,2017-09-28 09:21:21.000000,1.506590e+12,1.506591e+12,426,path426,1152,37,426,1.170371
4900,2017-09-28 09:26:47.000000,1.506591e+12,1.506591e+12,427,path427,3964,44,427,2.479762
4909,2017-09-28 09:28:19.000000,1.506591e+12,1.506591e+12,428,path428,593,41,428,1.204016
4918,2017-09-28 09:31:08.000000,1.506591e+12,1.506592e+12,429,path429,510,41,429,3.611573
4923,2017-09-28 09:32:17.000000,1.506591e+12,1.506591e+12,430,path430,3343,31,430,2.908970
4937,2017-09-28 09:32:18.000000,1.506591e+12,1.506591e+12,431,path431,1404,48,431,0.540352
4949,2017-09-28 09:35:44.000000,1.506591e+12,1.506592e+12,432,path432,3678,48,432,2.994662
4957,2017-09-28 10:38:45.000000,1.506595e+12,1.506596e+12,433,path433,2277,49,433,4.449664
4967,2017-09-28 10:39:02.000000,1.506595e+12,1.506596e+12,434,path434,1842,49,434,0.678919
4981,2017-09-28 10:43:10.000000,1.506596e+12,1.506596e+12,435,path435,684,50,435,4.968631
4998,2017-09-28 10:44:16.000000,1.506596e+12,1.506596e+12,436,path436,1655,50,436,1.669602

In [33]:
c=corr.merge(d,left_on='path_title',right_on='title')

In [34]:
c

,Correlation,rating_counts,path_title,time_zone,begin,end,pathId,title,id,user,path,rating
0,1.000000,14,path100,2017-03-27 14:00:05.000000,1.490623e+12,1.490626e+12,100,path100,4307,50,100,0.390067
1,1.000000,14,path356,2017-06-13 06:52:50.000000,1.497337e+12,1.497339e+12,356,path356,3699,37,356,3.255529
2,1.000000,16,path214,2017-03-30 09:37:57.000000,1.490867e+12,1.490867e+12,214,path214,4417,49,214,1.171585
3,1.000000,13,path208,2017-03-29 15:27:14.000000,1.490801e+12,1.490802e+12,208,path208,4439,48,208,2.342770
4,1.000000,15,path20,2016-06-23 08:35:24.000000,1.466671e+12,1.466671e+12,20,path20,2343,50,20,1.963985
5,1.000000,13,path383,2017-06-14 09:54:37.000000,1.497434e+12,1.497436e+12,383,path383,1709,50,383,1.590380
6,1.000000,19,path56,2016-11-15 11:29:42.000000,1.479209e+12,1.479210e+12,56,path56,4663,48,56,4.323428
7,1.000000,13,path61,2016-11-22 12:07:17.000000,1.479816e+12,1.479817e+12,61,path61,189,45,61,3.224625
8,1.000000,18,path362,2017-06-13 07:54:40.000000,1.497340e+12,1.497341e+12,362,path362,2122,48,362,2.100110
9,1.000000,15,path102,2017-03-27 14:46:33.000000,1.490626e+12,1.490627e+12,102,path102,1676,50,102,4.863677
10,1.000000,18,path310,2017-04-05 12:56:27.000000,1.491397e+12,1.491403e+12,310,path310,2910,45,310,3.883405
11,1.000000,14,path36,2016-07-15 16:26:52.000000,1.468600e+12,1.468600e+12,36,path36,3505,46,36,0.182561
12,1.000000,13,path25,2016-06-23 10:31:59.000000,1.466678e+12,1.466678e+12,25,path25,1580,49,25,3.578945
13,1.000000,14,path149,2017-03-28 14:51:41.000000,1.490713e+12,1.490713e+12,149,path149,4955,48,149,3.815665
14,1.000000,16,path89,2017-03-27 12:37:48.000000,1.490618e+12,1.490618e+12,89,path89,340,43,89,1.987720
15,1.000000,15,path138,2017-03-28 13:32:05.000000,1.490708e+12,1.490709e+12,138,path138,4497,50,138,3.057240
16,1.000000,13,path404,2017-06-21 06:59:31.000000,1.498029e+12,1.498030e+12,404,path404,333,49,404,0.132484
17,1.000000,13,path403,2017-06-15 07:09:04.000000,1.497511e+12,1.497511e+12,403,path403,2932,48,403,4.094609
18,1.000000,16,path16,2016-05-26 17:12:58.000000,1.464283e+12,1.464283e+12,16,path16,2241,50,16,3.257439
19,1.000000,17,path91,2017-03-27 12:46:43.000000,1.490619e+12,1.490619e+12,91,path91,3804,49,91,3.873134
20,0.999799,17,path320,2017-04-06 06:59:06.000000,1.491462e+12,1.491462e+12,320,path320,4819,47,320,4.908544
21,0.999658,15,path3,2016-04-11 10:41:57.000000,1.460371e+12,1.460372e+12,3,path3,3030,48,3,1.510361
22,0.989448,17,path254,2017-03-31 14:12:11.000000,1.490970e+12,1.490970e+12,254,path254,1206,44,254,0.888106
23,0.980086,16,path218,2017-03-30 09:46:59.000000,1.490867e+12,1.490868e+12,218,path218,1604,43,218,1.292364
24,0.957723,14,path435,2017-09-28 10:43:10.000000,1.506596e+12,1.506596e+12,435,path435,684,50,435,4.968631
25,0.948710,15,path140,2017-03-28 13:43:43.000000,1.490709e+12,1.490710e+12,140,path140,3100,50,140,4.864743
26,0.923911,13,path379,2017-06-14 07:05:17.000000,1.497424e+12,1.497433e+12,379,path379,1078,46,379,0.938152
27,0.825616,13,path8,2016-04-13 12:36:46.000000,1.460551e+12,1.460552e+12,8,path8,2330,43,8,0.911947
28,0.795967,13,path305,2017-04-05 12:21:12.000000,1.491395e+12,1.491395e+12,305,path305,1926,47,305,1.779418
29,0.758189,16,path26,2016-06-23 10:32:35.000000,1.466678e+12,1.466678e+12,26,path26,945,49,26,4.534497
...,...,...,...,...,...,...,...,...,...,...,...,...
108,-0.898719,16,path131,2017-03-28 10:54:23.000000,1.490698e+12,1.490699e+12,131,path131,1443,46,131,4.146013
109,-0.925114,13,path144,2017-03-28 14:05:22.000000,1.490710e+12,1.490711e+12,144,path144,708,47,144,2.276979
110,-0.937020,14,path193,2017-03-29 13:50:49.000000,1.490795e+12,1.490796e+12,193,path193,948,46,193,0.499097
111,-0.961758,14,path405,2017-06-21 09:09:32.000000,1.498036e+12,1.498038e+12,405,path405,3359,43,405,4.068294
112,-0.965265,16,path326,2017-04-06 11:07:34.000000,1.491477e+12,1.491478e+12,326,path326,251,49,326,3.876190
113,-0.983537,15,path112,2017-03-28 09:21:17.000000,1.490693e+12,1.490693e+12,112,path112,4430,49,112,1.471948
114,-0.988082,14,path382,2017-06-14 09:08:09.000000,1.497431e+12,1.497433e+12,382,path382,667,46,382,3.851378
115,-0.994823,21,path417,2017-09-28 08:33:53.000000,1.506588e+12,1.506589e+12,417,path417,1058,49,417,3.196748
116,-0.994860,13,path385,2017-06-14 10:56:26.000000,1.497438e+12,1.497438e+12,385,path385,4939,50,385,3.260952
117,-0.999991,13,path412,2017-09-28 08:20:06.000000,1.506590e+12,1.506592e+12,412,path412,4665,50,412,2.895333
118,-1.000000,14,path226,2017-03-30 10:41:58.000000,1.490871e+12,1.490871e+12,226,path226,1826,49,226,3.654840
119,-1.000000,18,path227,2017-03-30 10:45:35.000000,1.490871e+12,1.490871e+12,227,path227,449,49,227,3.991941
120,-1.000000,15,path338,2017-06-12 07:22:21.000000,1.497252e+12,1.497254e+12,338,path338,3550,49,338,0.601165
121,-1.000000,14,path90,2017-03-27 12:38:52.000000,1.490618e+12,1.490619e+12,90,path90,1357,39,90,3.617036
122,-1.000000,16,path133,2017-03-28 11:06:44.000000,1.490699e+12,1.490699e+12,133,path133,1830,49,133,0.730658
123,-1.000000,13,path18,2016-06-23 08:30:40.000000,1.466671e+12,1.466671e+12,18,path18,813,48,18,2.042635
124,-1.000000,14,path92,2017-03-27 12:49:21.000000,1.490619e+12,1.490619e+12,92,path92,3446,49,92,1.462613
125,-1.000000,15,path250,2017-03-31 13:58:47.000000,1.490969e+12,1.490970e+12,250,path250,2216,47,250,4.498253
126,-1.000000,18,path237,2017-03-30 14:59:48.000000,1.490886e+12,1.490889e+12,237,path237,299,43,237,1.418330
127,-1.000000,15,path260,2017-04-03 12:12:50.000000,1.491222e+12,1.491227e+12,260,path260,3250,46,260,0.908700
128,-1.000000,14,path267,2017-04-03 13:47:06.000000,1.491227e+12,1.491228e+12,267,path267,2840,46,267,1.821338
129,-1.000000,14,path30,2016-06-23 16:09:48.000000,1.466698e+12,1.466698e+12,30,path30,3506,40,30,2.602429
130,-1.000000,21,path302,2017-04-04 14:54:54.000000,1.491318e+12,1.491319e+12,302,path302,432,50,302,4.209160
131,-1.000000,14,path311,2017-04-05 14:51:58.000000,1.491404e+12,1.491404e+12,311,path311,902,50,311,2.424887
132,-1.000000,13,path359,2017-06-13 07:48:58.000000,1.497340e+12,1.497340e+12,359,path359,4606,50,359,1.173413
133,-1.000000,13,path315,2017-04-05 14:57:35.000000,1.491404e+12,1.491404e+12,315,path315,4671,50,315,3.487799
134,-1.000000,14,path316,2017-04-05 15:00:36.000000,1.491404e+12,1.491405e+12,316,path316,3987,49,316,2.687323
135,-1.000000,14,path32,2016-07-07 10:08:50.000000,1.467886e+12,1.467887e+12,32,path32,1227,48,32,1.884218
136,-1.000000,20,path322,2017-04-06 07:17:49.000000,1.491463e+12,1.491472e+12,322,path322,1723,46,322,2.911318
137,-1.000000,13,path309,2017-04-05 12:56:21.000000,1.491397e+12,1.491403e+12,309,path309,4769,47,309,0.137413